name: deploy python and nodeJS
on: push
jobs: 
  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: install python and nodeJS
      uses: ./.github/actions/cached-deps
      with:
        nodeversion: 18.20
        pythonversion: 3.10
