name: Deploy Python and NodeJS
on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Ensure full history so the action is up-to-date

      - name: Install Python and NodeJS
        id: build-setup
        uses: ./.github/actions/cached-deps-temp
        with:
          pythonversion: 3.9

      - name: Verify Node & Python versions
        shell: bash
        run: |
          node -v
          python --version

      - name: repo owner
        run: echo "repository owner = {{steps.build-setup.outputs.repoowner}}""