name: deploy python and nodeJS
on: push
jobs: 
  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: install python and nodeJS
      uses: ./.github/actions/cached-deps
      with:
        nodeversion: 18.18
        pythonversion: 3.8
