name: dispatch workflow
on:
 workflow_dispatch:
    inputs:
      name:
        description: "display workflow name"
        type: string
        required: false
        default: 'demo-workflow'
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: echo "${{inputs.name}}"
