name: dispatch workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "display workflow name"
        type: string
        required: false
        default: "demo-workflow"

      gender:
        description: "gender"
        type: choice
        required: true
        options:
          - male
          - female

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: display name
        run: echo "${{ inputs.name }}"

      - name: display gender
        run: echo " ${{inputs.gender }}"
