name: download artifacts
on: workflow_dispatch
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: artifact
          run-id: 20004434845
          github-token: ${{ github.token}}
          repository: ${{ github.repository}}

    