name: global-vars
on: push
jobs:
  var-job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: set global variables
       id: global-variables
       uses: ./.github/actions/globals
     - name: display the values of email and cicd key
       run: |
        echo "the email id is: ${{ steps.global-variables.outputs.email}}"
        echo "the CICD key is: ${{ steps.global-variables.outputs.CICDKey}}"
