name: job-output
on: push

jobs:
  sample-job:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.variable.outputs.name }}
    steps:
      - name: display message
        run: echo "greet"

      - name: provide the values
        id: variable
        run: echo "name=user1" >> $GITHUB_OUTPUT

  printjob:
    runs-on: ubuntu-latest
    needs: sample-job
    steps:
      - name: print the output
        run: echo "The user is: ${{ needs.sample-job.outputs.name }}"
