name: step-outputs
on: push
jobs:
  step-job:
    runs-on: ubuntu-latest
    steps:
      - name: write output
        id: set-output
        run: |
          echo "name=user1" >> $GITHUB_OUTPUT 
          echo "age-30" >> $GITHUB_OUTPUT
      - name: print output
        run: |
         ${{ steps.set-output.outputs.name}}
         ${{ steps.set-output.outputs.age}} 