name: step-outputs
on: push
jobs:
  step-job:
    runs-on: ubuntu-latest
    steps:
      - name: write output
        id: set-output
        run: echo "message= this is an example" >> $GITHUB_OUTPUT
      - name: print output
        run: echo ${{ steps.set-output.outputs.message}}