name: step-outputs
on: push
jobs:
  step-job:
    runs-on: ubuntu-latest
    steps:
      - name: write output
        id: step-output
        run: echo "this is an example" >> $GITHUB_OUTPUT
      - name: print output
        run: echo ${{ steps.outputs.step-output}}